# General Jekyll Config
highlighter: rouge
url: https://pierregillesleymarie.com
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock, node_modules, package.json, gulpfile.js]